name: Exécuter delays_gare_de_lyon

on:
  workflow_dispatch:    # permet de déclencher manuellement depuis GitHub
  schedule:
    - cron: '*/15 * * * *'  # (optionnel) toutes les 15 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Installer Python et dépendances
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install requests gtfs-realtime-bindings

      - name: Exécuter le script
        run: |
          python delays_gare_de_lyon.py > gdl-retard.txt

      - name: Afficher la sortie
        # Cette étape affiche le contenu du fichier généré
        run: cat gdl-retard.txt

      - name: Commit file to repository
<<<<<<< wi4u3f-codex/modifier-workflow-github-pour-écrire-dans-gdl-retard.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
>>>>>>> main
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add gdl-retard.txt
          git commit -m "Update gdl-retard.txt" || echo "No changes to commit"
<<<<<<< wi4u3f-codex/modifier-workflow-github-pour-écrire-dans-gdl-retard.txt
          git push "https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}" HEAD:${{ github.ref }}
=======
          git push
>>>>>>> main
